//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonOrder
    {
        public int OrderId { get; set; }
        public int PersonId { get; set; }
        public int RoomId { get; set; }
        public System.DateTime OrderStart { get; set; }
        public System.DateTime OrderEnd { get; set; }
        public bool OrderStatus { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Room Room { get; set; }
    }
}
