//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.PersonOrders = new HashSet<PersonOrder>();
        }
    
        public int RoomId { get; set; }
        public int TypeId { get; set; }
        public string RoomName { get; set; }
        public int RoomNo { get; set; }
        public int RoomBed { get; set; }
        public int RoomPerson { get; set; }
        public int RoomPrice { get; set; }
        public int RoomArea { get; set; }
        public byte[] RoomPicture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonOrder> PersonOrders { get; set; }
        public virtual TypeRoom TypeRoom { get; set; }
    }
}
