//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeRoom()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int TypeId { get; set; }
        public string NameRoom { get; set; }
        public bool AC { get; set; }
        public bool Hairdryer { get; set; }
        public bool Chair { get; set; }
        public bool Desk { get; set; }
        public bool Refrigerator { get; set; }
        public bool Balcony { get; set; }
        public bool Bathtub { get; set; }
        public bool Minibar { get; set; }
        public bool CoffeeMaker { get; set; }
        public bool SafetyBox { get; set; }
        public bool Champage { get; set; }
        public bool Kitchen { get; set; }
        public bool Bidet { get; set; }
        public bool Throne { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
